### ISSUE TITLE
ModuleNotFoundError: No module named 'pascal_voc_writer'

### ISSUE THREAD

**Issue by ajayvbabu** [mwindowshz/YoloToTfRecords#4]
/Users/ajayvbabu/x/aaaa/YoloToTfRecords/pascal_voc_writer/VisDrone/0000001_02999_d_0000005.jpg
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 359, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'pascal_voc_writer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "YoloToTfRecords/pascal_voc_writer/__init__.py", line 142, in <module>
    parse_yolo_labels(images_list_file_name=trainFiles,classes=classes)
  File "YoloToTfRecords/pascal_voc_writer/__init__.py", line 88, in parse_yolo_labels
    writer = Writer(imageFile, width=width, height=height)
  File "YoloToTfRecords/pascal_voc_writer/__init__.py", line 7, in __init__
    environment = Environment(loader=PackageLoader('pascal_voc_writer', 'templates'), keep_trailing_newline=True)
  File "/Users/ajayvbabu/Library/Python/3.7/lib/python/site-packages/jinja2/loaders.py", line 237, in __init__
    provider = get_provider(package_name)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 361, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'pascal_voc_writer'

**Comment by prak74** [comment]
There apparently exists a module named pascal_voc_writer on pip. Just install that using 
`pip install pascal_voc_writer`
